# Generated by Django 3.0.1 on 2020-08-13 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='a18usuarios',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, null=True)),
                ('nombres', models.CharField(max_length=200, null=True)),
                ('apellidos', models.CharField(max_length=200, null=True)),
                ('mail', models.CharField(max_length=200, null=True)),
                ('tipo', models.CharField(default='Usuario', max_length=100)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('fecha_crea', models.DateField(blank=True, null=True)),
                ('usuario_crea', models.CharField(max_length=100, null=True)),
                ('fecha_modi', models.DateField(blank=True, null=True)),
                ('usuario_modi', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'a18usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=55)),
                ('extension', models.CharField(max_length=5)),
                ('ubicacion', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Mes_Evento',
            fields=[
                ('id_mes', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=55)),
                ('mesCompleto', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id_principal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('eslogan', models.CharField(max_length=190)),
                ('image_eslogan', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('image_principal', models.ImageField(upload_to='', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_brigada',
            fields=[
                ('id_tipobrigada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_brigada', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_categoria',
            fields=[
                ('id_tipocat', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_noticia',
            fields=[
                ('id_tiponot', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_sugerencia',
            fields=[
                ('id_sug', models.AutoField(primary_key=True, serialize=False)),
                ('sugerencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=55)),
                ('descripcion', models.TextField(max_length=550)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('tipo_noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPSP.Tipo_noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=55)),
                ('hora', models.CharField(max_length=55)),
                ('descripcion', models.CharField(max_length=180)),
                ('lugar', models.CharField(max_length=55)),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPSP.Mes_Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=300)),
                ('correo', models.CharField(max_length=300)),
                ('rol', models.CharField(default='U', max_length=2)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=55, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='', verbose_name='Imagen')),
                ('auth_user', models.OneToOneField(db_column='auth_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IPSP.Tipo_categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Buzon_sugerencia',
            fields=[
                ('id_sugerencia', models.AutoField(primary_key=True, serialize=False)),
                ('sugerencia', models.CharField(max_length=300)),
                ('correo', models.CharField(max_length=65)),
                ('ubicacion', models.CharField(max_length=55)),
                ('tipo_sugerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPSP.Tipo_sugerencia')),
            ],
        ),
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id_brigada', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('miembro', models.TextField(max_length=200)),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('tipo_bri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPSP.Tipo_brigada')),
            ],
        ),
    ]
