# Generated by Django 3.0.1 on 2020-06-02 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IPSP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes_evento',
            name='mesCompleto',
            field=models.CharField(default=django.utils.timezone.now, max_length=75),
            preserve_default=False,
        ),
    ]
