# Generated by Django 3.0.1 on 2020-06-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPSP', '0002_mes_evento_mescompleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(max_length=550),
        ),
    ]
