# Generated by Django 3.0.1 on 2020-06-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPSP', '0003_auto_20200604_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id_principal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('eslogan', models.CharField(max_length=190)),
                ('image_eslogan', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('image_principal', models.ImageField(upload_to='', verbose_name='Imagen')),
            ],
        ),
    ]
