# Generated by Django 3.0.1 on 2020-07-08 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPSP', '0004_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_brigada',
            fields=[
                ('id_tipobrigada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_brigada', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id_brigada', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('miembro', models.TextField(max_length=200)),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('tipo_bri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPSP.Tipo_brigada')),
            ],
        ),
    ]
